<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Elsa.Specifications.PackageManifest.Generator.Core\Elsa.Specifications.PackageManifest.Generator.Core.csproj" />
  </ItemGroup>
</Project>
