<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\ValenceControl.PackageManifests\ValenceControl.PackageManifests.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="JsonSchema.Net" />
    <PackageReference Include="NuGet.Versioning" />
    <PackageReference Include="System.Reflection.MetadataLoadContext" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Overrides\Schemas\elsa-package.overrides.schema.json" />
  </ItemGroup>
</Project>
