<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <PackageId>Elsa.Platform.PackageManifest.Generator</PackageId>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <NoWarn>$(NoWarn);NU5100;NU5128</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Elsa.Platform.PackageManifest.Generator.MSBuild\Elsa.Platform.PackageManifest.Generator.MSBuild.csproj" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <None Include="build/**/*.*" Pack="true" PackagePath="build/" />
    <None Include="buildTransitive/**/*.*" Pack="true" PackagePath="buildTransitive/" />
    <None Include="README.md" Pack="true" PackagePath="/" />
    <Content Include="src/Elsa.Platform.PackageManifest.Generator.Hints/**/*.cs" Pack="true" PackagePath="contentFiles/cs/any/Elsa.Platform.PackageManifest.Generator.Hints/" BuildAction="Compile" />
    <Content Include="../Elsa.Platform.PackageManifest.Generator.MSBuild/bin/$(Configuration)/$(TargetFramework)/*.dll" Pack="true" PackagePath="tasks/" Condition="Exists('../Elsa.Platform.PackageManifest.Generator.MSBuild/bin/$(Configuration)/$(TargetFramework)/Elsa.Platform.PackageManifest.Generator.MSBuild.dll')" />
    <Content Include="../Elsa.Platform.PackageManifest.Generator.MSBuild/bin/$(Configuration)/$(TargetFramework)/Elsa.Platform.PackageManifest.Generator.MSBuild.deps.json" Pack="true" PackagePath="tasks/" Condition="Exists('../Elsa.Platform.PackageManifest.Generator.MSBuild/bin/$(Configuration)/$(TargetFramework)/Elsa.Platform.PackageManifest.Generator.MSBuild.deps.json')" />
  </ItemGroup>
</Project>
