<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JsonSchema.Net" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Schemas\**\*.json" />
    <None Include="README.md" Pack="true" PackagePath="/" />
  </ItemGroup>
</Project>
