<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Elsa.PackageManifest.Generator.Core\Elsa.PackageManifest.Generator.Core.csproj" />
    <ProjectReference Include="..\..\src\Elsa.PackageManifest.Generator.MSBuild\Elsa.PackageManifest.Generator.MSBuild.csproj" />
    <ProjectReference Include="..\Elsa.PackageManifest.Generator.Testing\Elsa.PackageManifest.Generator.Testing.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
